林子雨编著《数据采集与预处理》教材配套代码（教材官网）
查看所有章节代码

第8章 使用pandas进行数据清洗

In [133]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)  # 将列表转换为数组
print(b)

[1 2 3 4 5]


In [134]:
b.size  # 数组的元素个数

5

In [135]:
b.shape  # 数组的形状

(5,)

In [136]:
b.ndim  # 数组的维度

1

In [137]:
b.dtype  # 数据的元素类型

dtype('int32')

In [138]:
print(b[0], b[1], b[2])  #访问数组元素

1 2 3


In [139]:
b[4] = 6  # 修改数组元素
print(b)

[1 2 3 4 6]


In [140]:
c = np.array([[1, 2, 3], [4, 5, 6]])  # 创建二维数组
print(c.shape)  # 数组的形状
print(c[0, 0], c[0, 1], c[0, 2], c[1, 0], c[1, 1], c[1, 2])

(2, 3)
1 2 3 4 5 6


In [141]:
b = np.arange(24).reshape(2, 3, 4)
print(b.shape)
print(b)
print(b[:, 0, 0])  # 每层的第一行第一列

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0 12]


In [142]:
print("b[:, 1]:")
print(b[:, 1])

b[:, 1]:
[[ 4  5  6  7]
 [16 17 18 19]]


In [143]:
a = np.zeros([2, 3], int)
print(a)

[[0 0 0]
 [0 0 0]]


In [144]:
a = np.ones([2, 3], int)
print(a)

[[1 1 1]
 [1 1 1]]


In [145]:
a = np.empty([2, 3], int)
print(a)

[[0 0 0]
 [0 0 0]]


In [146]:
a = np.eye(3, k=1, dtype=int)  #对角矩阵，k控制为1的对角线位置
print(a)

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [147]:
a = np.full((2, 3), 4)  #全为4的矩阵
print(a)


[[4 4 4]
 [4 4 4]]


In [148]:
a = np.random.random((2, 3))
print(a)

[[0.89415975 0.95280881 0.37022162]
 [0.81218947 0.44856268 0.42330553]]


In [149]:
a = np.random.randint(2, size=10)
print(a)
b = np.random.randint(5, size=(2, 4))
print(b)

[1 1 0 1 0 0 0 1 1 1]
[[1 2 0 4]
 [0 4 1 1]]


In [150]:
a = np.random.rand(4,2)
print(a)

[[0.80294965 0.30602307]
 [0.95676595 0.37388864]
 [0.37508029 0.68299908]
 [0.97169771 0.20614759]]


### (9)randomrandn(): random.randn(d0,d1,...,dn)函返回一个或一组样本，具有标准正态分布,其中，dn表示每个维度的元素个数。

In [151]:
a = np.random.randn(2,4)
print(a)
# (9)randomrandn(): random.randnd0,d1,...,dn)函返回一个或一组样本，具有标准正态分布,其中，dn表示每个维度的元素个数。

[[-1.43959862  0.88164539  2.03953243 -1.55823596]
 [-1.55073958  0.37686229  1.06510724 -0.16091757]]


索引和切片

In [152]:
a = np.arange(10)
print(a)
print(a[5])
print(a[5:8])

a[5:8] = 12
print(a)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [153]:
a = np.arange(10)
a_slice = a[5:8]
a_slice[0] = -1
print(a_slice)
print(a)

[-1  6  7]
[ 0  1  2  3  4 -1  6  7  8  9]


多维数组

In [154]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[2])
print(b[0][2])
print(b[0,2])

[7 8 9]
3
3


In [155]:
print(b[:2])
print(b[:2,1:])


[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [156]:
print("#1",b[1,:2])
print("#2", b[:2,2])
print(b[:,:1])

#1 [4 5]
#2 [3 6]
[[1]
 [4]
 [7]]


## 数组运算

In [157]:
a = np.array([[1,2,3],[4,5,6]])

print(a*a)

[[ 1  4  9]
 [16 25 36]]


In [158]:
print(a-a)

[[0 0 0]
 [0 0 0]]


In [159]:
print(1/a)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [160]:
print(a+a)

[[ 2  4  6]
 [ 8 10 12]]


In [161]:
print(np.exp(a))
print(np.sqrt(a))
print(a**3)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  1   8  27]
 [ 64 125 216]]
